load("numdata.RData")
#Drop Year alone as it is not needed for training.
numdata1<-subset(numdata, select = -2)
set.seed(234)
ind<-sample(2, nrow(numdata1), replace = TRUE, prob=c(0.7,0.3))
trainset.model<-numdata1[ind == 1,]
testset.model<-numdata1[ind == 2,]
#Build SMOTE on trainset using UBL package
library(DMwR)
library(devtools)
library(UBL)
trainsetubl<-SmoteClassif(MCI~.,trainset.model, C.perc = "balance", dist="HEOM")
table(trainsetubl$MCI)
table(trainset.model$MCI)
prop.table(table(trainsetubl$MCI))
options(java.parameters = "-Xmx8g")
library(rJava)
library(RWeka)
library(RWekajars)
library(caret)
library(e1071)
# J48 Decision Tree
set.seed(243)
dtree.J48<-J48(MCI~., data=trainsetubl, control=Weka_control(M=100))
dtree.pred<-predict(dtree.J48, testset.model, type="class")
dtree.conf<-table(testset.model$MCI, dtree.pred, dnn=c("Actual", "Predicted"))
confusionMatrix(testset.model$MCI, dtree.pred)
evaluate_Weka_classifier(dtree.J48,  numFolds = 10) 
#implement KNN
set.seed(234)
knn.classifier<-IBk (MCI~., data=trainsetubl, control=Weka_control(K=3, X = TRUE))
evaluate_Weka_classifier(knn.classifier, numFolds = 10)
knn.pred<-predict(knn.classifier, testset.model, type="class")
knn.conf<-table(testset.model$MCI, knn.pred, dnn=c("Actual", "Predicted"))
confusionMatrix(testset.model$MCI, knn.pred)
#implement Naive Bayes
set.seed(234)
NB <- make_Weka_classifier("weka/classifiers/bayes/NaiveBayes")
b.classifier <- NB(MCI~., data=trainsetubl)
evaluate_Weka_classifier(b.classifier, numFolds = 10)
b.pred<-predict(b.classifier, testset.model, type="class")
b.conf<-table(testset.model$MCI, b.pred, dnn=c("Actual", "Predicted"))
confusionMatrix(testset.model$MCI, b.pred)
#implement Random Forest
set.seed(234)
RF<-make_Weka_classifier("weka/classifiers/trees/RandomForest")
rf.classifier<- RF(MCI~., data=trainsetubl)
evaluate_Weka_classifier(rf.classifier, numFolds = 10)
rf.pred<-predict(rf.classifier, testset.model, type="class")
rf.conf<-table(testset.model$MCI, rf.pred, dnn=c("Actual", "Predicted"))
confusionMatrix(testset.model$MCI, rf.pred)
