load("numdata.RData")
#Drop Year alone as it is not needed for training.
numdata<-subset(numdata, select = -2)
set.seed(123)
ind<-sample(2, nrow(numdata), replace = TRUE, prob=c(0.7,0.3))
trainset<-numdata[ind == 1,]
testset<-numdata[ind == 2,]
#Build SMOTE on trainset using UBL package
library(DMwR)
library(devtools)
library(UBL)
trainsetubl<-SmoteClassif(MCI~.,trainset, C.perc = "balance", dist="HEOM")
table(trainsetubl$MCI)
table(trainset$MCI)
prop.table(table(trainsetubl$MCI))
options(java.parameters = "-Xmx8g")
library(rJava)
library(RWeka)
library(RWekajars)
library(caret)
# J48 Decision Tree
set.seed(123)
dtree.J48<-J48(MCI~., data=trainsetubl, control=Weka_control(M=100))
dtree.pred<-predict(dtree.J48, testset, type="class")
dtree.conf<-table(testset$MCI, dtree.pred, dnn=c("Actual", "Predicted"))
confusionMatrix(testset$MCI, dtree.pred)
evaluate_Weka_classifier(dtree.J48,  numFolds = 10) 
#implement KNN
set.seed(123)
knn.classifier<-IBk (MCI~., data=trainsetubl, control=Weka_control(K=3, X = TRUE))
evaluate_Weka_classifier(knn.classifier, numFolds = 5)
knn.pred<-predict(knn.classifier, testset, type="class")
knn.conf<-table(testset$MCI, knn.pred, dnn=c("Actual", "Predicted"))
confusionMatrix(testset$MCI, knn.pred)
#implement Naive Bayes
set.seed(123)
NB <- make_Weka_classifier("weka/classifiers/bayes/NaiveBayes")
b.classifier <- NB(MCI~., data=trainsetubl)
evaluate_Weka_classifier(b.classifier, numFolds = 10)
b.pred<-predict(b.classifier, testset, type="class")
b.conf<-table(testset$MCI, b.pred, dnn=c("Actual", "Predicted"))
confusionMatrix(testset$MCI, b.pred)
#implement Random Forest
set.seed(123)
RF<-make_Weka_classifier("weka/classifiers/trees/RandomForest")
rf.classifier<- RF(MCI~., data=trainsetubl)
evaluate_Weka_classifier(rf.classifier, numFolds = 5)
rf.pred<-predict(rf.classifier, testset, type="class")
rf.conf<-table(testset$MCI, rf.pred, dnn=c("Actual", "Predicted"))
confusionMatrix(testset$MCI, rf.pred)
